[tool.pytest.ini_options]
addopts = "--cov-report html --cov=src/chess --cov=src/utils"
testpaths = [
    "tests",
]
markers = [
    "played_games",
]

[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"