DEFAULT_WINDOW_WIDTH: int = 660
DEFAULT_WINDOW_HEIGHT: int = 300

FONT_NAME: str = "Verdana"

BG_DARK: str = '#343A40'
BG_LIGHT: str = '#3B4754'
FG_LIGHT: str = '#FFF8DC'
FG_DARK: str = '#E0AF69'

SETTINGS_PAD: int = 15
START_PAGE_FRAME_PAD: int = 5
DEFAULT_FONT_SIZE: int = 13
FRAME_FONT_SIZE: int = 15
OFFLINE_PAGE_PAD: int = 10

LOCAL_CONFIG_PATH: str = 'src/config/user_config.txt'

MAX_ELO: int = 3544
MIN_ELO: int = 0
MAX_SKILL: int = 20
MIN_SKILL: int = 0