DEFAULT_WINDOW_WIDTH: int = 560
DEFAULT_WINDOW_HEIGHT: int = 300

FONT_NAME: str = "Verdana"

BG_DARK: str = '#343A40'
BG_LIGHT: str = '#3B4754'
FG_LIGHT: str = '#FFF8DC'
FG_DARK: str = '#E0AF69'

SETTINGS_PAD: int = 15
START_PAGE_FRAME_PAD: int = 5
DEFAULT_FONT_SIZE: int = 13
FRAME_FONT_SIZE: int = 15

LOCAL_CONFIG_PATH: str = 'src/config/user_config.txt'
