DEFAULT_WINDOW_WIDTH: int = 860
DEFAULT_WINDOW_HEIGHT: int = 300

FONT_NAME: str = "Verdana"

BG_DARK: str = '#343A40'
BG_LIGHT: str = '#3B4754'
FG_LIGHT: str = '#FFF8DC'
FG_DARK: str = '#E0AF69'

SETTINGS_PAD: int = 15
START_PAGE_FRAME_PAD: int = 5
TIME_ENTRY_PAD: int = 15
BOT_CONFIG_PAD: int = 10
DEFAULT_TIME_PAD: int = 5
OFFLINE_PAGE_PAD: int = 10
ONLINE_PAD: int = 10
SERVER_PAD: int = 10

RADIO_FONT_SIZE: int = 13
DEFAULT_FONT_SIZE: int = 13
FRAME_FONT_SIZE: int = 15

SCALE_LABEL_WIDTH: int = 8
TIME_ENTRY_WIDTH: int = 5
SETTINGS_MENUBUTTON_WIDTH: int = 11

LOCAL_CONFIG_PATH: str = 'src/config/user_config.txt'

MAX_ELO: int = 3544
MIN_ELO: int = 0
MAX_SKILL: int = 20
MIN_SKILL: int = 0
